pub enum Token {
    OP_PLUS,
    OP_MINUS,
    OP_MUL,
    OP_DIV,
    OP_MOD,
    OP_OR,
    OP_AND,
    OP_LOWER,
    OP_HIGHER,
    OP_IS,
    LOG_OR,
    LOG_AND,
    SHIFTL,
    SHIFTR,
    LOWER_EQ,
    EQUAL,
    NOTEQUAL,
    HIGHER_EQ,
    ISPLUS,
    ISMINUS,
    ISMUL,
    ISDIV,
    UN_PLUS,
    UN_MINUS,
    UN_NOT,
    UN_NEG,
    RET,
    CALL,
    CALLEXTERN,
    PUSHINT,
    PUSHVAR,
    PUSHSTR,
    PUSHINST,
    ASSIGNSTR,
    ASSIGNSTRP,
    ASSIGNFNC,
    ASSIGNFLOAT,
    ASSIGNINST,
    JUMP,
    JUMPF,
    SETINSTANCE,
    PUSH_ARRAYVAR
}

impl Token {
    pub fn byte_value(&self) -> u8 {
        match *self {
            OP_PLUS => 0,
            OP_MINUS => 1,
            OP_MUL => 2,
            OP_DIV => 3,
            OP_MOD => 4,
            OP_OR => 5,
            OP_AND => 6,
            OP_LOWER => 7,
            OP_HIGHER => 8,
            OP_IS => 9,
            LOG_OR => 11,
            LOG_AND => 12,
            SHIFTL => 13,
            SHIFTR => 14,
            LOWER_EQ => 15,
            EQUAL => 16,
            NOTEQUAL => 17,
            HIGHER_EQ => 18,
            ISPLUS => 19,
            ISMINUS => 20,
            ISMUL => 21,
            ISDIV => 22,
            UN_PLUS => 30,
            UN_MINUS => 31,
            UN_NOT => 32,
            UN_NEG => 33,
            RET => 60,
            CALL => 61,
            CALLEXTERN => 62,
            PUSHINT => 64,
            PUSHVAR => 65,
            PUSHSTR => 66,
            PUSHINST => 67,
            ASSIGNSTR => 70,
            ASSIGNSTRP => 71,
            ASSIGNFNC => 72,
            ASSIGNFLOAT => 73,
            ASSIGNINST => 74,
            JUMP => 75,
            JUMPF => 76,
            SETINSTANCE => 80,
            PUSH_ARRAYVAR => 245
        }
    }

    pub fn needs_param(&self) -> bool {
        match *self {
            OP_PLUS => false,
            OP_MINUS => false,
            OP_MUL => false,
            OP_DIV => false,
            OP_MOD => false,
            OP_OR => false,
            OP_AND => false,
            OP_LOWER => false,
            OP_HIGHER => false,
            OP_IS => false,
            LOG_OR => false,
            LOG_AND => false,
            SHIFTL => false,
            SHIFTR => false,
            LOWER_EQ => false,
            EQUAL => false,
            NOTEQUAL => false,
            HIGHER_EQ => false,
            ISPLUS => false,
            ISMINUS => false,
            ISMUL => false,
            ISDIV => false,
            UN_PLUS => false,
            UN_MINUS => false,
            UN_NOT => false,
            UN_NEG => false,
            RET => false,
            CALL => true,
            CALLEXTERN => true,
            PUSHINT => true,
            PUSHVAR => true,
            PUSHSTR => true,
            PUSHINST => true,
            ASSIGNSTR => false,
            ASSIGNSTRP => false,
            ASSIGNFNC => false,
            ASSIGNFLOAT => false,
            ASSIGNINST => false,
            JUMP => true,
            JUMPF => true,
            SETINSTANCE => true,
            PUSH_ARRAYVAR => false
        }
    }
}
