use crate::types::{parsed::zPAR_TYPE, External, Identifier, PrintableByteVec};

#[rustfmt::skip]
pub fn gothic2_externals() -> Vec<External> {
    let inst = Identifier::new(b"<inst>", (0, 0));
    vec![
        External { name: PrintableByteVec(b"INTTOSTRING".to_vec()), parameters: vec![zPAR_TYPE::Int], return_type: zPAR_TYPE::String, address: 6871264},
        External { name: PrintableByteVec(b"FLOATTOSTRING".to_vec()), parameters: vec![zPAR_TYPE::Float], return_type: zPAR_TYPE::String, address: 6871584},
        External { name: PrintableByteVec(b"FLOATTOINT".to_vec()), parameters: vec![zPAR_TYPE::Float], return_type: zPAR_TYPE::Int, address: 6871952},
        External { name: PrintableByteVec(b"INTTOFLOAT".to_vec()), parameters: vec![zPAR_TYPE::Int], return_type: zPAR_TYPE::Float, address: 6871904},
        External { name: PrintableByteVec(b"CONCATSTRINGS".to_vec()), parameters: vec![zPAR_TYPE::String, zPAR_TYPE::String], return_type: zPAR_TYPE::String, address: 6872000},
        External { name: PrintableByteVec(b"PRINT".to_vec()), parameters: vec![zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6872400},
        External { name: PrintableByteVec(b"PRINTDEBUG".to_vec()), parameters: vec![zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6872656},
        External { name: PrintableByteVec(b"PRINTSCREEN".to_vec()), parameters: vec![zPAR_TYPE::String, zPAR_TYPE::Int, zPAR_TYPE::Int, zPAR_TYPE::String, zPAR_TYPE::Int], return_type: zPAR_TYPE::Int, address: 6872912},
        External { name: PrintableByteVec(b"AI_PRINTSCREEN".to_vec()), parameters: vec![zPAR_TYPE::String, zPAR_TYPE::Int, zPAR_TYPE::Int, zPAR_TYPE::String, zPAR_TYPE::Int], return_type: zPAR_TYPE::Int, address: 6873632},
        External { name: PrintableByteVec(b"PRINTDIALOG".to_vec()), parameters: vec![zPAR_TYPE::Int, zPAR_TYPE::String, zPAR_TYPE::Int, zPAR_TYPE::Int, zPAR_TYPE::String, zPAR_TYPE::Int], return_type: zPAR_TYPE::Int, address: 6874640},
        External { name: PrintableByteVec(b"PRINTDEBUGINST".to_vec()), parameters: vec![zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6875424},
        External { name: PrintableByteVec(b"PRINTDEBUGINSTCH".to_vec()), parameters: vec![zPAR_TYPE::Int, zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6875824},
        External { name: PrintableByteVec(b"PRINTDEBUGCH".to_vec()), parameters: vec![zPAR_TYPE::Int, zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6876256},
        External { name: PrintableByteVec(b"PRINTMULTI".to_vec()), parameters: vec![zPAR_TYPE::String, zPAR_TYPE::String, zPAR_TYPE::String, zPAR_TYPE::String, zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6876544},
        External { name: PrintableByteVec(b"EXITGAME".to_vec()), parameters: vec![], return_type: zPAR_TYPE::Void, address: 6974176},
        External { name: PrintableByteVec(b"EXITSESSION".to_vec()), parameters: vec![], return_type: zPAR_TYPE::Void, address: 6974208},
        External { name: PrintableByteVec(b"PLAYVIDEO".to_vec()), parameters: vec![zPAR_TYPE::String], return_type: zPAR_TYPE::Int, address: 6813536},
        External { name: PrintableByteVec(b"PLAYVIDEOEX".to_vec()), parameters: vec![zPAR_TYPE::String, zPAR_TYPE::Int, zPAR_TYPE::Int], return_type: zPAR_TYPE::Int, address: 6813760},
        External { name: PrintableByteVec(b"SETPERCENTDONE".to_vec()), parameters: vec![zPAR_TYPE::Int], return_type: zPAR_TYPE::Void, address: 6974240},
        External { name: PrintableByteVec(b"INTRODUCECHAPTER".to_vec()), parameters: vec![zPAR_TYPE::String, zPAR_TYPE::String, zPAR_TYPE::String, zPAR_TYPE::String, zPAR_TYPE::Int], return_type: zPAR_TYPE::Void, address: 6973072},
        External { name: PrintableByteVec(b"NPC_MEMORYENTRY".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int, zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int, zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6840368},
        External { name: PrintableByteVec(b"NPC_MEMORYENTRYGUILD".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int, zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int, zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6843056},
        External { name: PrintableByteVec(b"NPC_HASNEWS".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int, zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6941760},
        External { name: PrintableByteVec(b"NPC_GETNEWSWITNESS".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int], return_type: zPAR_TYPE::Instance(inst.clone()), address: 6942416},
        External { name: PrintableByteVec(b"NPC_GETNEWSOFFENDER".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int], return_type: zPAR_TYPE::Instance(inst.clone()), address: 6943280},
        External { name: PrintableByteVec(b"NPC_GETNEWSVICTIM".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int], return_type: zPAR_TYPE::Instance(inst.clone()), address: 6944144},
        External { name: PrintableByteVec(b"NPC_ISNEWSGOSSIP".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int], return_type: zPAR_TYPE::Int, address: 6945008},
        External { name: PrintableByteVec(b"NPC_DELETENEWS".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int], return_type: zPAR_TYPE::Int, address: 6945872},
        External { name: PrintableByteVec(b"NPC_GETGUILDATTITUDE".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6884784},
        External { name: PrintableByteVec(b"NPC_GETACTIVESPELL".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6883120},
        External { name: PrintableByteVec(b"NPC_GETLASTHITSPELLID".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6883344},
        External { name: PrintableByteVec(b"NPC_GETLASTHITSPELLCAT".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6883616},
        External { name: PrintableByteVec(b"NPC_GETACTIVESPELLCAT".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6884112},
        External { name: PrintableByteVec(b"NPC_GETACTIVESPELLLEVEL".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6884336},
        External { name: PrintableByteVec(b"NPC_GETACTIVESPELLISSCROLL".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6884560},
        External { name: PrintableByteVec(b"NPC_SETACTIVESPELLINFO".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int], return_type: zPAR_TYPE::Int, address: 6883888},
        External { name: PrintableByteVec(b"WLD_DETECTITEM".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int], return_type: zPAR_TYPE::Int, address: 6864880},
        External { name: PrintableByteVec(b"WLD_DETECTPLAYER".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6865344},
        External { name: PrintableByteVec(b"WLD_DETECTNPC".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int, zPAR_TYPE::Func, zPAR_TYPE::Int], return_type: zPAR_TYPE::Int, address: 6865792},
        External { name: PrintableByteVec(b"WLD_DETECTNPCEX".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int, zPAR_TYPE::Func, zPAR_TYPE::Int, zPAR_TYPE::Int], return_type: zPAR_TYPE::Int, address: 6866800},
        External { name: PrintableByteVec(b"WLD_DETECTNPCEXATT".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int, zPAR_TYPE::Func, zPAR_TYPE::Int, zPAR_TYPE::Int, zPAR_TYPE::Int], return_type: zPAR_TYPE::Int, address: 6867824},
        External { name: PrintableByteVec(b"WLD_SETGUILDATTITUDE".to_vec()), parameters: vec![zPAR_TYPE::Int, zPAR_TYPE::Int, zPAR_TYPE::Int], return_type: zPAR_TYPE::Void, address: 6868864},
        External { name: PrintableByteVec(b"WLD_GETGUILDATTITUDE".to_vec()), parameters: vec![zPAR_TYPE::Int, zPAR_TYPE::Int], return_type: zPAR_TYPE::Int, address: 6868960},
        External { name: PrintableByteVec(b"WLD_ISMOBAVAILABLE".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::String], return_type: zPAR_TYPE::Int, address: 6950864},
        External { name: PrintableByteVec(b"WLD_ISFPAVAILABLE".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::String], return_type: zPAR_TYPE::Int, address: 6907744},
        External { name: PrintableByteVec(b"WLD_ISNEXTFPAVAILABLE".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::String], return_type: zPAR_TYPE::Int, address: 6908432},
        External { name: PrintableByteVec(b"NPC_CREATESPELL".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int], return_type: zPAR_TYPE::Void, address: 6957552},
        External { name: PrintableByteVec(b"NPC_LEARNSPELL".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int], return_type: zPAR_TYPE::Void, address: 6889136},
        External { name: PrintableByteVec(b"NPC_HASITEMS".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int], return_type: zPAR_TYPE::Int, address: 6890640},
        External { name: PrintableByteVec(b"NPC_GIVEITEM".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int, zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6890896},
        External { name: PrintableByteVec(b"CREATEINVITEM".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int], return_type: zPAR_TYPE::Void, address: 6891472},
        External { name: PrintableByteVec(b"CREATEINVITEMS".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int, zPAR_TYPE::Int], return_type: zPAR_TYPE::Void, address: 6892816},
        External { name: PrintableByteVec(b"NPC_GETINVITEM".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int], return_type: zPAR_TYPE::Int, address: 6922416},
        External { name: PrintableByteVec(b"NPC_GETINVITEMBYSLOT".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int, zPAR_TYPE::Int], return_type: zPAR_TYPE::Int, address: 6922704},
        External { name: PrintableByteVec(b"NPC_REMOVEINVITEM".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int], return_type: zPAR_TYPE::Int, address: 6893376},
        External { name: PrintableByteVec(b"NPC_REMOVEINVITEMS".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int, zPAR_TYPE::Int], return_type: zPAR_TYPE::Int, address: 6894512},
        External { name: PrintableByteVec(b"NPC_CLEARINVENTORY".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6893888},
        External { name: PrintableByteVec(b"NPC_ISINSTATE".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Func], return_type: zPAR_TYPE::Int, address: 6881664},
        External { name: PrintableByteVec(b"NPC_WASINSTATE".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Func], return_type: zPAR_TYPE::Int, address: 6881904},
        External { name: PrintableByteVec(b"NPC_ISINROUTINE".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Func], return_type: zPAR_TYPE::Int, address: 6882160},
        External { name: PrintableByteVec(b"AI_SETNPCSTOSTATE".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Func, zPAR_TYPE::Int], return_type: zPAR_TYPE::Void, address: 6882768},
        External { name: PrintableByteVec(b"NPC_HASDETECTEDNPC".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6895952},
        External { name: PrintableByteVec(b"NPC_SETATTITUDE".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int], return_type: zPAR_TYPE::Void, address: 6896880},
        External { name: PrintableByteVec(b"NPC_SETTEMPATTITUDE".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int], return_type: zPAR_TYPE::Void, address: 6897104},
        External { name: PrintableByteVec(b"NPC_GETATTITUDE".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6897328},
        External { name: PrintableByteVec(b"NPC_GETPERMATTITUDE".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6897776},
        External { name: PrintableByteVec(b"NPC_CHANGEATTRIBUTE".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int, zPAR_TYPE::Int], return_type: zPAR_TYPE::Void, address: 6896624},
        External { name: PrintableByteVec(b"NPC_GETCOMRADES".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6941536},
        External { name: PrintableByteVec(b"NPC_ISNEAR".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6934816},
        External { name: PrintableByteVec(b"NPC_GETDISTTONPC".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6936912},
        External { name: PrintableByteVec(b"NPC_GETHEIGHTTONPC".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6937376},
        External { name: PrintableByteVec(b"NPC_GETHEIGHTTOITEM".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6937728},
        External { name: PrintableByteVec(b"NPC_GETDISTTOPLAYER".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6939440},
        External { name: PrintableByteVec(b"NPC_GETDISTTOITEM".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6938976},
        External { name: PrintableByteVec(b"NPC_GETDISTTOWP".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::String], return_type: zPAR_TYPE::Int, address: 6938080},
        External { name: PrintableByteVec(b"NPC_CANSEENPC".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6935520},
        External { name: PrintableByteVec(b"NPC_CANSEENPCFREELOS".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6935984},
        External { name: PrintableByteVec(b"NPC_CANSEEITEM".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6936448},
        External { name: PrintableByteVec(b"NPC_ISPLAYER".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6935280},
        External { name: PrintableByteVec(b"NPC_KNOWSPLAYER".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6920688},
        External { name: PrintableByteVec(b"NPC_SETKNOWSPLAYER".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6921168},
        External { name: PrintableByteVec(b"NPC_ISINFIGHTMODE".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int], return_type: zPAR_TYPE::Int, address: 6885232},
        External { name: PrintableByteVec(b"NPC_ISAIMING".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6885472},
        External { name: PrintableByteVec(b"NPC_STARTITEMREACTMODULES".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6898432},
        External { name: PrintableByteVec(b"NPC_HASOFFERED".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int], return_type: zPAR_TYPE::Int, address: 6900336},
        External { name: PrintableByteVec(b"EQUIPITEM".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int], return_type: zPAR_TYPE::Void, address: 6895120},
        External { name: PrintableByteVec(b"NPC_SETTOFISTMODE".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6889360},
        External { name: PrintableByteVec(b"NPC_SETTOFIGHTMODE".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int], return_type: zPAR_TYPE::Void, address: 6889664},
        External { name: PrintableByteVec(b"NPC_ISDEAD".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6896400},
        External { name: PrintableByteVec(b"AI_STARTSTATE".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Func, zPAR_TYPE::Int, zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6869632},
        External { name: PrintableByteVec(b"AI_CONTINUEROUTINE".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6869040},
        External { name: PrintableByteVec(b"NPC_GETSTATETIME".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6870800},
        External { name: PrintableByteVec(b"NPC_SETSTATETIME".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int], return_type: zPAR_TYPE::Void, address: 6871024},
        External { name: PrintableByteVec(b"AI_OUTPUT".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6901984},
        External { name: PrintableByteVec(b"AI_OUTPUTSVM".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6902640},
        External { name: PrintableByteVec(b"AI_OUTPUTSVM_OVERLAY".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6903184},
        External { name: PrintableByteVec(b"AI_PLAYCUTSCENE".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6903728},
        External { name: PrintableByteVec(b"AI_CANSEENPC".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Func], return_type: zPAR_TYPE::Void, address: 6927584},
        External { name: PrintableByteVec(b"AI_WAIT".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Float], return_type: zPAR_TYPE::Void, address: 6904928},
        External { name: PrintableByteVec(b"AI_WAITMS".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int], return_type: zPAR_TYPE::Void, address: 6905280},
        External { name: PrintableByteVec(b"AI_WAITTILLEND".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6905616},
        External { name: PrintableByteVec(b"AI_ALIGNTOWP".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6919504},
        External { name: PrintableByteVec(b"AI_SETWALKMODE".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int], return_type: zPAR_TYPE::Void, address: 6912432},
        External { name: PrintableByteVec(b"AI_PLAYANI".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6904112},
        External { name: PrintableByteVec(b"AI_PLAYANIBS".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::String, zPAR_TYPE::Int], return_type: zPAR_TYPE::Void, address: 6904512},
        External { name: PrintableByteVec(b"AI_GOTOWP".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6906112},
        External { name: PrintableByteVec(b"AI_TELEPORT".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6854064},
        External { name: PrintableByteVec(b"AI_GOTOITEM".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6906976},
        External { name: PrintableByteVec(b"AI_GOTONPC".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6906560},
        External { name: PrintableByteVec(b"AI_ALIGNTOFP".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6909808},
        External { name: PrintableByteVec(b"AI_GOTOFP".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6910288},
        External { name: PrintableByteVec(b"NPC_ISONFP".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::String], return_type: zPAR_TYPE::Int, address: 6909120},
        External { name: PrintableByteVec(b"AI_GOTONEXTFP".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6911008},
        External { name: PrintableByteVec(b"AI_GOTOSOUND".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6907392},
        External { name: PrintableByteVec(b"AI_TAKEITEM".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6931664},
        External { name: PrintableByteVec(b"AI_DROPITEM".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int], return_type: zPAR_TYPE::Void, address: 6932224},
        External { name: PrintableByteVec(b"AI_DRAWWEAPON".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6911680},
        External { name: PrintableByteVec(b"AI_REMOVEWEAPON".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6912000},
        External { name: PrintableByteVec(b"NPC_HASRANGEDWEAPONWITHAMMO".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6885920},
        External { name: PrintableByteVec(b"NPC_HASEQUIPPEDWEAPON".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6886144},
        External { name: PrintableByteVec(b"NPC_HASEQUIPPEDMELEEWEAPON".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6886624},
        External { name: PrintableByteVec(b"NPC_HASEQUIPPEDRANGEDWEAPON".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6887104},
        External { name: PrintableByteVec(b"NPC_HASEQUIPPEDARMOR".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6887584},
        External { name: PrintableByteVec(b"NPC_HASREADIEDWEAPON".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6886384},
        External { name: PrintableByteVec(b"NPC_HASREADIEDMELEEWEAPON".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6886864},
        External { name: PrintableByteVec(b"NPC_HASREADIEDRANGEDWEAPON".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6887344},
        External { name: PrintableByteVec(b"NPC_GETTRUEGUILD".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6919984},
        External { name: PrintableByteVec(b"NPC_SETTRUEGUILD".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int], return_type: zPAR_TYPE::Int, address: 6920208},
        External { name: PrintableByteVec(b"NPC_AREWESTRONGER".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6912768},
        External { name: PrintableByteVec(b"NPC_GETTARGET".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6913744},
        External { name: PrintableByteVec(b"NPC_GETNEXTTARGET".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6914160},
        External { name: PrintableByteVec(b"NPC_GETLOOKATTARGET".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Instance(inst.clone()), address: 6914864},
        External { name: PrintableByteVec(b"NPC_ISNEXTTARGETAVAILABLE".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6914624},
        External { name: PrintableByteVec(b"NPC_SETTARGET".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6913232},
        External { name: PrintableByteVec(b"NPC_GETBODYSTATE".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6941056},
        External { name: PrintableByteVec(b"NPC_HASBODYFLAG".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int], return_type: zPAR_TYPE::Int, address: 6941280},
        External { name: PrintableByteVec(b"NPC_ISINCUTSCENE".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6855264},
        External { name: PrintableByteVec(b"NPC_ISVOICEACTIVE".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6855504},
        External { name: PrintableByteVec(b"NPC_STOPANI".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6855760},
        External { name: PrintableByteVec(b"NPC_GETDETECTEDMOB".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::String, address: 6915168},
        External { name: PrintableByteVec(b"NPC_PLAYANI".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6882416},
        External { name: PrintableByteVec(b"NPC_ISDETECTEDMOBOWNEDBYNPC".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6915824},
        External { name: PrintableByteVec(b"NPC_ISDETECTEDMOBOWNEDBYGUILD".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int], return_type: zPAR_TYPE::Int, address: 6916352},
        External { name: PrintableByteVec(b"WLD_GETMOBSTATE".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::String], return_type: zPAR_TYPE::Int, address: 6916656},
        External { name: PrintableByteVec(b"NPC_CLEARAIQUEUE".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6919296},
        External { name: PrintableByteVec(b"INFOMANAGER_HASFINISHED".to_vec()), parameters: vec![], return_type: zPAR_TYPE::Int, address: 6844336},
        External { name: PrintableByteVec(b"AI_STOPPROCESSINFOS".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6843584},
        External { name: PrintableByteVec(b"AI_PROCESSINFOS".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6843952},
        External { name: PrintableByteVec(b"INFO_ADDCHOICE".to_vec()), parameters: vec![zPAR_TYPE::Int, zPAR_TYPE::String, zPAR_TYPE::Func], return_type: zPAR_TYPE::Void, address: 6844368},
        External { name: PrintableByteVec(b"INFO_CLEARCHOICES".to_vec()), parameters: vec![zPAR_TYPE::Int], return_type: zPAR_TYPE::Void, address: 6845264},
        External { name: PrintableByteVec(b"NPC_KNOWSINFO".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int], return_type: zPAR_TYPE::Int, address: 6846032},
        External { name: PrintableByteVec(b"NPC_CHECKINFO".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int], return_type: zPAR_TYPE::Int, address: 6846816},
        External { name: PrintableByteVec(b"NPC_GIVEINFO".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int], return_type: zPAR_TYPE::Int, address: 6847104},
        External { name: PrintableByteVec(b"NPC_GETTALENTSKILL".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int], return_type: zPAR_TYPE::Int, address: 6887824},
        External { name: PrintableByteVec(b"NPC_GETTALENTVALUE".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int], return_type: zPAR_TYPE::Int, address: 6888352},
        External { name: PrintableByteVec(b"NPC_SETTALENTSKILL".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int, zPAR_TYPE::Int], return_type: zPAR_TYPE::Void, address: 6888080},
        External { name: PrintableByteVec(b"NPC_SETTALENTVALUE".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int, zPAR_TYPE::Int], return_type: zPAR_TYPE::Void, address: 6888608},
        External { name: PrintableByteVec(b"TAL_CONFIGURE".to_vec()), parameters: vec![zPAR_TYPE::Int, zPAR_TYPE::Int], return_type: zPAR_TYPE::Void, address: 6888880},
        External { name: PrintableByteVec(b"NPC_GETNEARESTWP".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::String, address: 6917952},
        External { name: PrintableByteVec(b"NPC_GETNEXTWP".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::String, address: 6918592},
        External { name: PrintableByteVec(b"NPC_ISWAYBLOCKED".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6901584},
        External { name: PrintableByteVec(b"NPC_GETREADIEDWEAPON".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Instance(inst.clone()), address: 6917056},
        External { name: PrintableByteVec(b"NPC_GETEQUIPPEDMELEEWEAPON".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Instance(inst.clone()), address: 6917280},
        External { name: PrintableByteVec(b"NPC_GETEQUIPPEDRANGEDWEAPON".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Instance(inst.clone()), address: 6917504},
        External { name: PrintableByteVec(b"NPC_GETEQUIPPEDARMOR".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Instance(inst.clone()), address: 6917728},
        External { name: PrintableByteVec(b"AI_EQUIPBESTMELEEWEAPON".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6923168},
        External { name: PrintableByteVec(b"AI_EQUIPBESTRANGEDWEAPON".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6923488},
        External { name: PrintableByteVec(b"AI_EQUIPBESTARMOR".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6923808},
        External { name: PrintableByteVec(b"AI_UNEQUIPWEAPONS".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6924128},
        External { name: PrintableByteVec(b"AI_UNEQUIPARMOR".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6924448},
        External { name: PrintableByteVec(b"AI_EQUIPARMOR".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int], return_type: zPAR_TYPE::Void, address: 6924768},
        External { name: PrintableByteVec(b"AI_READYMELEEWEAPON".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6925312},
        External { name: PrintableByteVec(b"AI_READYRANGEDWEAPON".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6925648},
        External { name: PrintableByteVec(b"AI_TURNAWAY".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6925984},
        External { name: PrintableByteVec(b"AI_TURNTONPC".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6926400},
        External { name: PrintableByteVec(b"AI_WHIRLAROUND".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6926816},
        External { name: PrintableByteVec(b"AI_WHIRLAROUNDTOSOURCE".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6927232},
        External { name: PrintableByteVec(b"AI_TURNTOSOUND".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6928016},
        External { name: PrintableByteVec(b"AI_QUICKLOOK".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6928368},
        External { name: PrintableByteVec(b"AI_LOOKAT".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6929200},
        External { name: PrintableByteVec(b"AI_LOOKATNPC".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6928784},
        External { name: PrintableByteVec(b"AI_STOPLOOKAT".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6929904},
        External { name: PrintableByteVec(b"AI_POINTAT".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6930640},
        External { name: PrintableByteVec(b"AI_POINTATNPC".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6930224},
        External { name: PrintableByteVec(b"AI_STOPPOINTAT".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6931344},
        External { name: PrintableByteVec(b"AI_STANDUP".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6946176},
        External { name: PrintableByteVec(b"AI_STANDUPQUICK".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6946528},
        External { name: PrintableByteVec(b"AI_FLEE".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6947280},
        External { name: PrintableByteVec(b"AI_AIMAT".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6947520},
        External { name: PrintableByteVec(b"AI_STOPAIM".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6947936},
        External { name: PrintableByteVec(b"AI_SHOOTAT".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6948256},
        External { name: PrintableByteVec(b"AI_DEFEND".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6946864},
        External { name: PrintableByteVec(b"AI_COMBATREACTTODAMAGE".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6948912},
        External { name: PrintableByteVec(b"AI_READYSPELL".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int, zPAR_TYPE::Int], return_type: zPAR_TYPE::Void, address: 6948928},
        External { name: PrintableByteVec(b"AI_UNREADYSPELL".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6949296},
        External { name: PrintableByteVec(b"NPC_HASSPELL".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int], return_type: zPAR_TYPE::Int, address: 6949616},
        External { name: PrintableByteVec(b"AI_ATTACK".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6948672},
        External { name: PrintableByteVec(b"AI_FINISHINGMOVE".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6949872},
        External { name: PrintableByteVec(b"AI_DODGE".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6950544},
        External { name: PrintableByteVec(b"AI_USEITEM".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int], return_type: zPAR_TYPE::Void, address: 6932880},
        External { name: PrintableByteVec(b"AI_USEITEMTOSTATE".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int, zPAR_TYPE::Int], return_type: zPAR_TYPE::Void, address: 6933840},
        External { name: PrintableByteVec(b"NPC_REFUSETALK".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6955200},
        External { name: PrintableByteVec(b"NPC_SETREFUSETALK".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int], return_type: zPAR_TYPE::Void, address: 6955440},
        External { name: PrintableByteVec(b"AI_ASK".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Func, zPAR_TYPE::Func], return_type: zPAR_TYPE::Void, address: 6955680},
        External { name: PrintableByteVec(b"AI_ASKTEXT".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Func, zPAR_TYPE::Func, zPAR_TYPE::String, zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6956240},
        External { name: PrintableByteVec(b"AI_WAITFORQUESTION".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Func], return_type: zPAR_TYPE::Void, address: 6956816},
        External { name: PrintableByteVec(b"HLP_ISITEM".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int], return_type: zPAR_TYPE::Int, address: 6957168},
        External { name: PrintableByteVec(b"HLP_GETINSTANCEID".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6957424},
        External { name: PrintableByteVec(b"HLP_RANDOM".to_vec()), parameters: vec![zPAR_TYPE::Int], return_type: zPAR_TYPE::Int, address: 6957504},
        External { name: PrintableByteVec(b"HLP_STRCMP".to_vec()), parameters: vec![zPAR_TYPE::String, zPAR_TYPE::String], return_type: zPAR_TYPE::Int, address: 6921616},
        External { name: PrintableByteVec(b"HLP_GETNPC".to_vec()), parameters: vec![zPAR_TYPE::Int], return_type: zPAR_TYPE::Instance(inst.clone()), address: 6922176},
        External { name: PrintableByteVec(b"HLP_ISVALIDNPC".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6922352},
        External { name: PrintableByteVec(b"HLP_ISVALIDITEM".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6923104},
        External { name: PrintableByteVec(b"AI_SND_PLAY".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6962496},
        External { name: PrintableByteVec(b"AI_SND_PLAY3D".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6963168},
        External { name: PrintableByteVec(b"SND_PLAY".to_vec()), parameters: vec![zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6961472},
        External { name: PrintableByteVec(b"SND_PLAY3D".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6961648},
        External { name: PrintableByteVec(b"SND_GETDISTTOSOURCE".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6964080},
        External { name: PrintableByteVec(b"SND_ISSOURCENPC".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6964320},
        External { name: PrintableByteVec(b"SND_ISSOURCEITEM".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6964800},
        External { name: PrintableByteVec(b"NPC_CANSEESOURCE".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6965280},
        External { name: PrintableByteVec(b"MIS_GETSTATUS".to_vec()), parameters: vec![zPAR_TYPE::Int], return_type: zPAR_TYPE::Int, address: 6960640},
        External { name: PrintableByteVec(b"MIS_SETSTATUS".to_vec()), parameters: vec![zPAR_TYPE::Int, zPAR_TYPE::Int], return_type: zPAR_TYPE::Void, address: 6961392},
        External { name: PrintableByteVec(b"MIS_ONTIME".to_vec()), parameters: vec![zPAR_TYPE::Int], return_type: zPAR_TYPE::Int, address: 6961392},
        External { name: PrintableByteVec(b"LOG_CREATETOPIC".to_vec()), parameters: vec![zPAR_TYPE::String, zPAR_TYPE::Int], return_type: zPAR_TYPE::Void, address: 6876752},
        External { name: PrintableByteVec(b"LOG_ADDENTRY".to_vec()), parameters: vec![zPAR_TYPE::String, zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6877088},
        External { name: PrintableByteVec(b"LOG_SETTOPICSTATUS".to_vec()), parameters: vec![zPAR_TYPE::String, zPAR_TYPE::Int], return_type: zPAR_TYPE::Void, address: 6877376},
        External { name: PrintableByteVec(b"MIS_ADDMISSIONENTRY".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6877616},
        External { name: PrintableByteVec(b"MIS_REMOVEMISSION".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6878432},
        External { name: PrintableByteVec(b"NPC_CHECKAVAILABLEMISSION".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int, zPAR_TYPE::Int], return_type: zPAR_TYPE::Int, address: 6957776},
        External { name: PrintableByteVec(b"NPC_CHECKRUNNINGMISSION".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int], return_type: zPAR_TYPE::Int, address: 6959264},
        External { name: PrintableByteVec(b"NPC_ISDRAWINGWEAPON".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6958480},
        External { name: PrintableByteVec(b"NPC_ISDRAWINGSPELL".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6958896},
        External { name: PrintableByteVec(b"NPC_CHECKOFFERMISSION".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int], return_type: zPAR_TYPE::Int, address: 6959952},
        External { name: PrintableByteVec(b"MDL_SETVISUAL".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6965520},
        External { name: PrintableByteVec(b"MDL_SETVISUALBODY".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::String, zPAR_TYPE::Int, zPAR_TYPE::Int, zPAR_TYPE::String, zPAR_TYPE::Int, zPAR_TYPE::Int, zPAR_TYPE::Int], return_type: zPAR_TYPE::Void, address: 6966160},
        External { name: PrintableByteVec(b"MDL_APPLYOVERLAYMDS".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6967024},
        External { name: PrintableByteVec(b"MDL_APPLYOVERLAYMDSTIMED".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::String, zPAR_TYPE::Int], return_type: zPAR_TYPE::Void, address: 6967680},
        External { name: PrintableByteVec(b"MDL_REMOVEOVERLAYMDS".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6968336},
        External { name: PrintableByteVec(b"MDL_APPLYRANDOMANI".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::String, zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6968992},
        External { name: PrintableByteVec(b"MDL_APPLYRANDOMANIFREQ".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::String, zPAR_TYPE::Float], return_type: zPAR_TYPE::Void, address: 6969968},
        External { name: PrintableByteVec(b"MDL_SETMODELSCALE".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Float, zPAR_TYPE::Float, zPAR_TYPE::Float], return_type: zPAR_TYPE::Void, address: 6970784},
        External { name: PrintableByteVec(b"MDL_SETMODELFATNESS".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Float], return_type: zPAR_TYPE::Void, address: 6971120},
        External { name: PrintableByteVec(b"MDL_STARTFACEANI".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::String, zPAR_TYPE::Float, zPAR_TYPE::Float], return_type: zPAR_TYPE::Void, address: 6971344},
        External { name: PrintableByteVec(b"MDL_APPLYRANDOMFACEANI".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::String, zPAR_TYPE::Float, zPAR_TYPE::Float, zPAR_TYPE::Float, zPAR_TYPE::Float, zPAR_TYPE::Float], return_type: zPAR_TYPE::Void, address: 6972016},
        External { name: PrintableByteVec(b"WLD_ISTIME".to_vec()), parameters: vec![zPAR_TYPE::Int, zPAR_TYPE::Int, zPAR_TYPE::Int, zPAR_TYPE::Int], return_type: zPAR_TYPE::Int, address: 6972816},
        External { name: PrintableByteVec(b"WLD_GETDAY".to_vec()), parameters: vec![], return_type: zPAR_TYPE::Int, address: 6972928},
        External { name: PrintableByteVec(b"WLD_ISRAINING".to_vec()), parameters: vec![], return_type: zPAR_TYPE::Int, address: 6972976},
        External { name: PrintableByteVec(b"WLD_SETTIME".to_vec()), parameters: vec![zPAR_TYPE::Int, zPAR_TYPE::Int], return_type: zPAR_TYPE::Void, address: 6852592},
        External { name: PrintableByteVec(b"WLD_INSERTNPC".to_vec()), parameters: vec![zPAR_TYPE::Int, zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6857632},
        External { name: PrintableByteVec(b"WLD_SPAWNNPCRANGE".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int, zPAR_TYPE::Int, zPAR_TYPE::Float], return_type: zPAR_TYPE::Void, address: 6859248},
        External { name: PrintableByteVec(b"WLD_PLAYEFFECT".to_vec()), parameters: vec![zPAR_TYPE::String, zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int, zPAR_TYPE::Int, zPAR_TYPE::Int, zPAR_TYPE::Int], return_type: zPAR_TYPE::Void, address: 6860240},
        External { name: PrintableByteVec(b"WLD_STOPEFFECT".to_vec()), parameters: vec![zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6874208},
        External { name: PrintableByteVec(b"AI_PLAYFX".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6860736},
        External { name: PrintableByteVec(b"AI_STOPFX".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6861264},
        External { name: PrintableByteVec(b"WLD_REMOVENPC".to_vec()), parameters: vec![zPAR_TYPE::Int], return_type: zPAR_TYPE::Void, address: 6858496},
        External { name: PrintableByteVec(b"WLD_INSERTNPCANDRESPAWN".to_vec()), parameters: vec![zPAR_TYPE::Int, zPAR_TYPE::String, zPAR_TYPE::Int], return_type: zPAR_TYPE::Void, address: 6861632},
        External { name: PrintableByteVec(b"WLD_INSERTITEM".to_vec()), parameters: vec![zPAR_TYPE::Int, zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6862544},
        External { name: PrintableByteVec(b"WLD_INSERTOBJECT".to_vec()), parameters: vec![zPAR_TYPE::String, zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6863392},
        External { name: PrintableByteVec(b"WLD_REMOVEITEM".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6864528},
        External { name: PrintableByteVec(b"WLD_EXCHANGEGUILDATTITUDES".to_vec()), parameters: vec![zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6864688},
        External { name: PrintableByteVec(b"WLD_SETOBJECTROUTINE".to_vec()), parameters: vec![zPAR_TYPE::Int, zPAR_TYPE::Int, zPAR_TYPE::String, zPAR_TYPE::Int], return_type: zPAR_TYPE::Void, address: 6856288},
        External { name: PrintableByteVec(b"WLD_SETMOBROUTINE".to_vec()), parameters: vec![zPAR_TYPE::Int, zPAR_TYPE::Int, zPAR_TYPE::String, zPAR_TYPE::Int], return_type: zPAR_TYPE::Void, address: 6856960},
        External { name: PrintableByteVec(b"WLD_SENDTRIGGER".to_vec()), parameters: vec![zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6852752},
        External { name: PrintableByteVec(b"WLD_SENDUNTRIGGER".to_vec()), parameters: vec![zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6853408},
        External { name: PrintableByteVec(b"NPC_OWNEDBYNPC".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6900848},
        External { name: PrintableByteVec(b"NPC_OWNEDBYGUILD".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int], return_type: zPAR_TYPE::Int, address: 6901328},
        External { name: PrintableByteVec(b"AI_TAKEMOB".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6952304},
        External { name: PrintableByteVec(b"AI_DROPMOB".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6952960},
        External { name: PrintableByteVec(b"AI_USEMOB".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::String, zPAR_TYPE::Int], return_type: zPAR_TYPE::Int, address: 6951552},
        External { name: PrintableByteVec(b"MOB_CREATEITEMS".to_vec()), parameters: vec![zPAR_TYPE::String, zPAR_TYPE::Int, zPAR_TYPE::Int], return_type: zPAR_TYPE::Void, address: 6953472},
        External { name: PrintableByteVec(b"MOB_HASITEMS".to_vec()), parameters: vec![zPAR_TYPE::String, zPAR_TYPE::Int], return_type: zPAR_TYPE::Int, address: 6954528},
        External { name: PrintableByteVec(b"DOC_CREATE".to_vec()), parameters: vec![], return_type: zPAR_TYPE::Int, address: 6835584},
        External { name: PrintableByteVec(b"DOC_CREATEMAP".to_vec()), parameters: vec![], return_type: zPAR_TYPE::Int, address: 6835520},
        External { name: PrintableByteVec(b"DOC_SETPAGES".to_vec()), parameters: vec![zPAR_TYPE::Int, zPAR_TYPE::Int], return_type: zPAR_TYPE::Void, address: 6835648},
        External { name: PrintableByteVec(b"DOC_SETPAGE".to_vec()), parameters: vec![zPAR_TYPE::Int, zPAR_TYPE::Int, zPAR_TYPE::String, zPAR_TYPE::Int], return_type: zPAR_TYPE::Void, address: 6835760},
        External { name: PrintableByteVec(b"DOC_SETFONT".to_vec()), parameters: vec![zPAR_TYPE::Int, zPAR_TYPE::Int, zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6836304},
        External { name: PrintableByteVec(b"DOC_SETLEVEL".to_vec()), parameters: vec![zPAR_TYPE::Int, zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6836592},
        External { name: PrintableByteVec(b"DOC_SETLEVELCOORDS".to_vec()), parameters: vec![zPAR_TYPE::Int, zPAR_TYPE::Int, zPAR_TYPE::Int, zPAR_TYPE::Int, zPAR_TYPE::Int], return_type: zPAR_TYPE::Void, address: 6836832},
        External { name: PrintableByteVec(b"DOC_SETMARGINS".to_vec()), parameters: vec![zPAR_TYPE::Int, zPAR_TYPE::Int, zPAR_TYPE::Int, zPAR_TYPE::Int, zPAR_TYPE::Int, zPAR_TYPE::Int, zPAR_TYPE::Int], return_type: zPAR_TYPE::Void, address: 6836064},
        External { name: PrintableByteVec(b"DOC_PRINTLINE".to_vec()), parameters: vec![zPAR_TYPE::Int, zPAR_TYPE::Int, zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6837008},
        External { name: PrintableByteVec(b"DOC_PRINTLINES".to_vec()), parameters: vec![zPAR_TYPE::Int, zPAR_TYPE::Int, zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6837296},
        External { name: PrintableByteVec(b"DOC_SHOW".to_vec()), parameters: vec![zPAR_TYPE::Int], return_type: zPAR_TYPE::Void, address: 6837584},
        External { name: PrintableByteVec(b"DOC_OPEN".to_vec()), parameters: vec![zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6837664},
        External { name: PrintableByteVec(b"DOC_FONT".to_vec()), parameters: vec![zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6838976},
        External { name: PrintableByteVec(b"DOC_PRINT".to_vec()), parameters: vec![zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6838400},
        External { name: PrintableByteVec(b"DOC_MAPCOORDINATES".to_vec()), parameters: vec![zPAR_TYPE::String, zPAR_TYPE::Float, zPAR_TYPE::Float, zPAR_TYPE::Float, zPAR_TYPE::Float, zPAR_TYPE::Float, zPAR_TYPE::Float, zPAR_TYPE::Float, zPAR_TYPE::Float], return_type: zPAR_TYPE::Void, address: 6839552},
        External { name: PrintableByteVec(b"TA".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int, zPAR_TYPE::Int, zPAR_TYPE::Func, zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6847392},
        External { name: PrintableByteVec(b"TA_MIN".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int, zPAR_TYPE::Int, zPAR_TYPE::Int, zPAR_TYPE::Int, zPAR_TYPE::Func, zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6848080},
        External { name: PrintableByteVec(b"TA_CS".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::String, zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6848800},
        External { name: PrintableByteVec(b"TA_BEGINOVERLAY".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6849568},
        External { name: PrintableByteVec(b"TA_ENDOVERLAY".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6849792},
        External { name: PrintableByteVec(b"TA_REMOVEOVERLAY".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6850016},
        External { name: PrintableByteVec(b"NPC_EXCHANGEROUTINE".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6851840},
        External { name: PrintableByteVec(b"RTN_EXCHANGE".to_vec()), parameters: vec![zPAR_TYPE::String, zPAR_TYPE::String], return_type: zPAR_TYPE::Void, address: 6850240},
        External { name: PrintableByteVec(b"PERC_SETRANGE".to_vec()), parameters: vec![zPAR_TYPE::Int, zPAR_TYPE::Int], return_type: zPAR_TYPE::Void, address: 6854480},
        External { name: PrintableByteVec(b"NPC_SETPERCTIME".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Float], return_type: zPAR_TYPE::Void, address: 6854544},
        External { name: PrintableByteVec(b"NPC_PERCENABLE".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int, zPAR_TYPE::Func], return_type: zPAR_TYPE::Void, address: 6854784},
        External { name: PrintableByteVec(b"NPC_PERCDISABLE".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int], return_type: zPAR_TYPE::Void, address: 6855040},
        External { name: PrintableByteVec(b"NPC_SENDPASSIVEPERC".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int, zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6939696},
        External { name: PrintableByteVec(b"NPC_SENDSINGLEPERC".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Instance(inst.clone()), zPAR_TYPE::Int], return_type: zPAR_TYPE::Void, address: 6940336},
        External { name: PrintableByteVec(b"NPC_PERCEIVEALL".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6898224},
        External { name: PrintableByteVec(b"WLD_ASSIGNROOMTOGUILD".to_vec()), parameters: vec![zPAR_TYPE::String, zPAR_TYPE::Int], return_type: zPAR_TYPE::Void, address: 6880160},
        External { name: PrintableByteVec(b"WLD_ASSIGNROOMTONPC".to_vec()), parameters: vec![zPAR_TYPE::String, zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Void, address: 6879536},
        External { name: PrintableByteVec(b"WLD_GETPLAYERPORTALOWNER".to_vec()), parameters: vec![], return_type: zPAR_TYPE::Instance(inst.clone()), address: 6879216},
        External { name: PrintableByteVec(b"WLD_GETPLAYERPORTALGUILD".to_vec()), parameters: vec![], return_type: zPAR_TYPE::Int, address: 6879408},
        External { name: PrintableByteVec(b"WLD_GETFORMERPLAYERPORTALOWNER".to_vec()), parameters: vec![], return_type: zPAR_TYPE::Instance(inst.clone()), address: 6879312},
        External { name: PrintableByteVec(b"WLD_GETFORMERPLAYERPORTALGUILD".to_vec()), parameters: vec![], return_type: zPAR_TYPE::Int, address: 6879472},
        External { name: PrintableByteVec(b"NPC_ISPLAYERINMYROOM".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6880368},
        External { name: PrintableByteVec(b"NPC_ISINPLAYERSROOM".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6880608},
        External { name: PrintableByteVec(b"NPC_WASPLAYERINMYROOM".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6880848},
        External { name: PrintableByteVec(b"NPC_GETPORTALOWNER".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Instance(inst.clone()), address: 6881088},
        External { name: PrintableByteVec(b"NPC_GETPORTALGUILD".to_vec()), parameters: vec![zPAR_TYPE::Instance(inst.clone())], return_type: zPAR_TYPE::Int, address: 6881424},
        External { name: PrintableByteVec(b"HLP_CUTSCENEPLAYED".to_vec()), parameters: vec![zPAR_TYPE::String], return_type: zPAR_TYPE::Int, address: 6921984},
        External { name: PrintableByteVec(b"GAME_INITGERMAN".to_vec()), parameters: vec![], return_type: zPAR_TYPE::Int, address: 6974288},
        External { name: PrintableByteVec(b"GAME_INITENGLISH".to_vec()), parameters: vec![], return_type: zPAR_TYPE::Int, address: 6974320},
        External { name: PrintableByteVec(b"GAME_INITENGINTL".to_vec()), parameters: vec![], return_type: zPAR_TYPE::Int, address: 6974352},
    ]
}
